name: Tests FastAPI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.13]
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3
    
    - name: Installer Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        cd backend 
        pip install -r requirements.txt
    
    - name: Lancer les tests
      run: |
        cd backend 
        pytest Test.py -v --cov=./

    - name: Formatage black
      run: |
        black --check


